{{- if .Values.mongodbExpress.enabled -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mongo-express
spec:
  rules:
    - host: {{ .Values.mongodbExpress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ .Release.Name }}-service
                port:
                  number: 8081
{{- end -}}
